### ISSUE TITLE
How to pass data into the signature function

### ISSUE THREAD

**Issue by wtglad** [ldarrick/PathSignatures#1]
Hi there, I may just be missing something basic, but I am having a hard time figuring out the best way to pass arguments into the signature function. I tried loading a dataframe from CSV, converting it into an array, and calling the signature via `signature(Array(df), 2,'R')`, but then get the error: 

```
UndefVarError: p not defined

Stacktrace:
 [1] discrete_derivative(::Array{Float64,2}, ::Char) at C:\Users\wtgla\Documents\Research\PathSignatures.jl:235
 [2] signature(::Array{Float64,2}, ::Int64, ::Char) at C:\Users\wtgla\Documents\Research\PathSignatures.jl:281
 [3] top-level scope at In[4]:1
 [4] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```

So I then tried explicitly specifying `p` via `signature(p = Array(df), m = 2, dtype='R')` but get an  ` unsupported keyword argument "p"`  error:

```
MethodError: no method matching signature(; p=[0.0 2.136477624379761 2.163306748094372; 1000.0 2.136477624379761 2.3099622601813152; … ; 412000.0 1.4962199044045155 1.4871339360659994; 413000.0 1.9384299560198723 1.5451737478872007], m=2, dtype='R')
Closest candidates are:
  signature(!Matched::Any, !Matched::Any, !Matched::Any) at C:\Users\wtgla\Documents\Research\PathSignatures.jl:278 got unsupported keyword arguments "p", "m", "dtype"

Stacktrace:
 [1] top-level scope at In[3]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```
I get similar results if I use the argument `P` instead of `p`. I also thought it might be an issue with using the continuous signature, but I get the same results if I use the discrete `dsignature` method as well. 

Any tips here? Thanks in advance!

**Comment by ldarrick** [comment]
Hey,

The issue is that dtype should be passed as a string rather than a char. It should work if you try calling it as `signature(Array(df), 2, "R")` with the double quotes.

Hope that helps!

**Comment by wtglad** [comment]
Ah - that seems to work. Thank you!
